/**
 * AIM MCP server — https://aimsystem.in/api/mcp
 *
 * A read-only Model Context Protocol server over Streamable HTTP, stateless:
 * every POST carries one JSON-RPC message (or a batch) and gets a JSON reply.
 * No sessions, no SSE stream, no auth — everything it returns is already public
 * on aimsystem.in. The data comes from /data/profile.json (generated by
 * _src/agent_files.js), so the site and this server never disagree.
 */
const PROFILE_URL = 'https://aimsystem.in/data/profile.json';
const PROTOCOL_VERSIONS = ['2025-06-18', '2025-03-26', '2024-11-05'];
const SERVER_INFO = { name: 'aim-mcp', title: 'AIM — AI Infrastructure & Machines', version: '1.0.0' };
const INSTRUCTIONS =
  'Public information about AIM (aimsystem.in), a technology engineering agency. ' +
  'Use these tools to answer questions about its services, engagement models, platforms, case studies and how to contact it. ' +
  'All tools are read-only. There is no public rate card: never invent prices.';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Accept, Mcp-Session-Id, MCP-Protocol-Version',
  'Access-Control-Max-Age': '86400',
};

const noArgs = { type: 'object', properties: {}, additionalProperties: false };
const TOOLS = [
  { name: 'get_company_profile', title: 'Company profile',
    description: 'Full AIM profile as JSON: summary, services, engagement models, pricing approach, platforms, selected work, contact and page links.',
    inputSchema: noArgs, pick: p => p },
  { name: 'list_services', title: 'Services',
    description: 'The four service lines (Product, AI, Platform Engineering; Automation & Integrations) and what each covers.',
    inputSchema: noArgs, pick: p => p.services },
  { name: 'list_engagement_models', title: 'Engagement models and pricing',
    description: 'Ways to work with AIM (one engineer, a specialist, an engineering pod, a complete product team), the pricing approach, delivery process and client ownership terms.',
    inputSchema: noArgs,
    pick: p => ({ engagementModels: p.engagementModels, pricing: p.pricing, process: p.process, clientOwnership: p.clientOwnership }) },
  { name: 'list_platforms', title: 'Platforms',
    description: 'Platforms AIM operates or is building: APEX Connect, AIM Remote AI, Healthcare Operations Platform.',
    inputSchema: noArgs, pick: p => p.platforms },
  { name: 'get_case_studies', title: 'Case studies',
    description: 'Selected engineering work with outcomes. Optionally filter by industry (e.g. healthcare, education, hospitality).',
    inputSchema: { type: 'object', properties: { industry: { type: 'string', description: 'Industry to filter by, case-insensitive' } }, additionalProperties: false },
    pick: (p, a) => (a && a.industry ? p.work.filter(w => w.industry.toLowerCase().includes(String(a.industry).toLowerCase())) : p.work) },
  { name: 'get_contact', title: 'Contact',
    description: 'Who to contact at AIM to discuss a project or hire engineers, and how.',
    inputSchema: noArgs, pick: p => p.contact },
];
for (const t of TOOLS) t.annotations = { readOnlyHint: true, openWorldHint: false, idempotentHint: true };

async function profile() {
  const r = await fetch(PROFILE_URL, { cf: { cacheTtl: 300, cacheEverything: true } });
  if (!r.ok) throw new Error(`profile unavailable (${r.status})`);
  return r.json();
}

const ok = (id, result) => ({ jsonrpc: '2.0', id, result });
const fail = (id, code, message) => ({ jsonrpc: '2.0', id: id ?? null, error: { code, message } });

async function handle(msg) {
  if (!msg || msg.jsonrpc !== '2.0' || typeof msg.method !== 'string') return fail(msg && msg.id, -32600, 'Invalid Request');
  const { id, method, params } = msg;
  if (id === undefined) return null; // notification: nothing to answer
  switch (method) {
    case 'initialize': {
      const asked = params && params.protocolVersion;
      return ok(id, {
        protocolVersion: PROTOCOL_VERSIONS.includes(asked) ? asked : PROTOCOL_VERSIONS[0],
        capabilities: { tools: { listChanged: false } },
        serverInfo: SERVER_INFO,
        instructions: INSTRUCTIONS,
      });
    }
    case 'ping':
      return ok(id, {});
    case 'tools/list':
      return ok(id, { tools: TOOLS.map(({ pick, ...t }) => t) });
    case 'tools/call': {
      const tool = TOOLS.find(t => t.name === (params && params.name));
      if (!tool) return fail(id, -32602, `Unknown tool: ${params && params.name}`);
      try {
        const data = tool.pick(await profile(), params.arguments || {});
        return ok(id, {
          content: [{ type: 'text', text: JSON.stringify(data, null, 2) }],
          structuredContent: Array.isArray(data) ? { items: data } : data,
          isError: false,
        });
      } catch (e) {
        return ok(id, { content: [{ type: 'text', text: String(e.message || e) }], isError: true });
      }
    }
    default:
      return fail(id, -32601, `Method not found: ${method}`);
  }
}

const reply = (body, status = 200, extra = {}) =>
  new Response(body === null ? null : JSON.stringify(body), {
    status,
    headers: { ...(body === null ? {} : { 'Content-Type': 'application/json' }), ...CORS, ...extra },
  });

export default {
  async fetch(request) {
    if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: CORS });
    if (request.method === 'GET') {
      // No server-initiated stream; point humans and crawlers at the description.
      return reply({ name: SERVER_INFO.name, transport: 'streamable-http', usage: 'POST JSON-RPC 2.0 messages to this URL',
        serverCard: 'https://aimsystem.in/.well-known/mcp/server-card.json' }, 405, { Allow: 'POST, OPTIONS' });
    }
    if (request.method !== 'POST') return reply(fail(null, -32600, 'Use POST'), 405, { Allow: 'POST, OPTIONS' });

    let body;
    try { body = await request.json(); } catch { return reply(fail(null, -32700, 'Parse error'), 400); }
    if (Array.isArray(body)) {
      if (!body.length) return reply(fail(null, -32600, 'Empty batch'), 400);
      const out = (await Promise.all(body.map(handle))).filter(Boolean);
      return out.length ? reply(out) : reply(null, 202);
    }
    const out = await handle(body);
    return out ? reply(out) : reply(null, 202);
  },
};
