// Writes ../assets/js/icons.js with only the Lucide icons the site uses,
// plus a tiny window.lucide.createIcons() that swaps <i data-lucide> for SVG.
const fs = require('fs');
const path = require('path');
const lucide = require('lucide');

const sources = [
  ...fs.readdirSync(path.join(__dirname, 'pages')).map(f => path.join(__dirname, 'pages', f)),
  path.join(__dirname, 'build.py'),
  path.join(__dirname, '..', 'assets', 'js', 'aim.js'),
];
const names = new Set(['sun', 'moon', 'menu', 'x', 'volume-2', 'volume-x']); // toggled at runtime
for (const f of sources) {
  for (const m of fs.readFileSync(f, 'utf8').matchAll(/data-lucide="([a-z0-9-]+)"/g)) names.add(m[1]);
}
const pascal = n => n.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const out = {};
for (const n of [...names].sort()) {
  const node = lucide[pascal(n)];
  if (!node) { console.error('unknown icon:', n); process.exitCode = 1; continue; }
  out[n] = node[2];
}
const js = `/* Lucide icons (ISC licence), subset generated by _src/icons.js */
(function () {
  var I = ${JSON.stringify(out)};
  function el(tag, attrs) {
    var e = document.createElementNS('http://www.w3.org/2000/svg', tag);
    for (var k in attrs) e.setAttribute(k, attrs[k]);
    return e;
  }
  function createIcons() {
    document.querySelectorAll('[data-lucide]').forEach(function (n) {
      var name = n.getAttribute('data-lucide'), kids = I[name];
      if (!kids || n.getAttribute('data-rendered') === name) return;
      var s = el('svg', { xmlns: 'http://www.w3.org/2000/svg', width: 24, height: 24, viewBox: '0 0 24 24', fill: 'none',
        stroke: 'currentColor', 'stroke-width': 2, 'stroke-linecap': 'round', 'stroke-linejoin': 'round', 'aria-hidden': 'true' });
      kids.forEach(function (c) { s.appendChild(el(c[0], c[1])); });
      for (var i = 0; i < n.attributes.length; i++) {
        var a = n.attributes[i];
        if (a.name !== 'data-lucide') s.setAttribute(a.name, a.value);
      }
      s.setAttribute('data-rendered', name);
      var cls = (n.getAttribute('class') || '').replace(/\blucide(-[a-z0-9-]+)?\b/g, '').trim();
      s.setAttribute('class', 'lucide lucide-' + name + ' ' + cls);
      n.replaceWith(s);
    });
  }
  window.lucide = { createIcons: createIcons };
  createIcons();
})();
`;
fs.writeFileSync(path.join(__dirname, '..', 'assets', 'js', 'icons.js'), js);
console.log(`icons.js: ${Object.keys(out).length} icons, ${js.length} bytes`);
